version: '2'
services:
  web:
    container_name: nome.instancia
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - '8004:80'
    volumes:
      - ./:/app
    dns: 
      - '8.8.8.8'
      - '8.8.4.4'
    networks:
      - dev-net

  db:
    container_name: db.nome.instancia
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    networks:
      - dev-net
    volumes:
      - ./db/:/var/lib/postgresql/data
      
networks:
  dev-net:
    external: true